/**
 * Copyright (c) 2015-2017 Obeo, Inria
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 	
 * Contributors:
 * - William Piers <william.piers@obeo.fr>
 * - Philippe Merle <philippe.merle@inria.fr>
 * - Faiez Zalila <faiez.zalila@inria.fr>
 */
package org.occiware.clouddesigner.occi.simulation.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import org.occiware.clouddesigner.occi.simulation.util.SimulationAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class SimulationItemProviderAdapterFactory extends SimulationAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public SimulationItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.occiware.clouddesigner.occi.simulation.Computesim} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComputesimItemProvider computesimItemProvider;

	/**
	 * This creates an adapter for a {@link org.occiware.clouddesigner.occi.simulation.Computesim}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createComputesimAdapter() {
		if (computesimItemProvider == null) {
			computesimItemProvider = new ComputesimItemProvider(this);
		}

		return computesimItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.occiware.clouddesigner.occi.simulation.Storagesim} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StoragesimItemProvider storagesimItemProvider;

	/**
	 * This creates an adapter for a {@link org.occiware.clouddesigner.occi.simulation.Storagesim}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStoragesimAdapter() {
		if (storagesimItemProvider == null) {
			storagesimItemProvider = new StoragesimItemProvider(this);
		}

		return storagesimItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.occiware.clouddesigner.occi.simulation.Networksim} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NetworksimItemProvider networksimItemProvider;

	/**
	 * This creates an adapter for a {@link org.occiware.clouddesigner.occi.simulation.Networksim}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNetworksimAdapter() {
		if (networksimItemProvider == null) {
			networksimItemProvider = new NetworksimItemProvider(this);
		}

		return networksimItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.occiware.clouddesigner.occi.simulation.Datacenter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DatacenterItemProvider datacenterItemProvider;

	/**
	 * This creates an adapter for a {@link org.occiware.clouddesigner.occi.simulation.Datacenter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDatacenterAdapter() {
		if (datacenterItemProvider == null) {
			datacenterItemProvider = new DatacenterItemProvider(this);
		}

		return datacenterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.occiware.clouddesigner.occi.simulation.Cloudlet} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CloudletItemProvider cloudletItemProvider;

	/**
	 * This creates an adapter for a {@link org.occiware.clouddesigner.occi.simulation.Cloudlet}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCloudletAdapter() {
		if (cloudletItemProvider == null) {
			cloudletItemProvider = new CloudletItemProvider(this);
		}

		return cloudletItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.occiware.clouddesigner.occi.simulation.Host} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected HostItemProvider hostItemProvider;

	/**
	 * This creates an adapter for a {@link org.occiware.clouddesigner.occi.simulation.Host}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createHostAdapter() {
		if (hostItemProvider == null) {
			hostItemProvider = new HostItemProvider(this);
		}

		return hostItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.occiware.clouddesigner.occi.simulation.Vm} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VmItemProvider vmItemProvider;

	/**
	 * This creates an adapter for a {@link org.occiware.clouddesigner.occi.simulation.Vm}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVmAdapter() {
		if (vmItemProvider == null) {
			vmItemProvider = new VmItemProvider(this);
		}

		return vmItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.occiware.clouddesigner.occi.simulation.Harddrivestorage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected HarddrivestorageItemProvider harddrivestorageItemProvider;

	/**
	 * This creates an adapter for a {@link org.occiware.clouddesigner.occi.simulation.Harddrivestorage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createHarddrivestorageAdapter() {
		if (harddrivestorageItemProvider == null) {
			harddrivestorageItemProvider = new HarddrivestorageItemProvider(this);
		}

		return harddrivestorageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.occiware.clouddesigner.occi.simulation.Sanstorage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SanstorageItemProvider sanstorageItemProvider;

	/**
	 * This creates an adapter for a {@link org.occiware.clouddesigner.occi.simulation.Sanstorage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSanstorageAdapter() {
		if (sanstorageItemProvider == null) {
			sanstorageItemProvider = new SanstorageItemProvider(this);
		}

		return sanstorageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.occiware.clouddesigner.occi.simulation.Probadistrib} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ProbadistribItemProvider probadistribItemProvider;

	/**
	 * This creates an adapter for a {@link org.occiware.clouddesigner.occi.simulation.Probadistrib}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createProbadistribAdapter() {
		if (probadistribItemProvider == null) {
			probadistribItemProvider = new ProbadistribItemProvider(this);
		}

		return probadistribItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.occiware.clouddesigner.occi.simulation.Poisson} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PoissonItemProvider poissonItemProvider;

	/**
	 * This creates an adapter for a {@link org.occiware.clouddesigner.occi.simulation.Poisson}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPoissonAdapter() {
		if (poissonItemProvider == null) {
			poissonItemProvider = new PoissonItemProvider(this);
		}

		return poissonItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.occiware.clouddesigner.occi.simulation.Gauss} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GaussItemProvider gaussItemProvider;

	/**
	 * This creates an adapter for a {@link org.occiware.clouddesigner.occi.simulation.Gauss}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGaussAdapter() {
		if (gaussItemProvider == null) {
			gaussItemProvider = new GaussItemProvider(this);
		}

		return gaussItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.occiware.clouddesigner.occi.simulation.Binomiale} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BinomialeItemProvider binomialeItemProvider;

	/**
	 * This creates an adapter for a {@link org.occiware.clouddesigner.occi.simulation.Binomiale}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBinomialeAdapter() {
		if (binomialeItemProvider == null) {
			binomialeItemProvider = new BinomialeItemProvider(this);
		}

		return binomialeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.occiware.clouddesigner.occi.simulation.Pricestrategies} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PricestrategiesItemProvider pricestrategiesItemProvider;

	/**
	 * This creates an adapter for a {@link org.occiware.clouddesigner.occi.simulation.Pricestrategies}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPricestrategiesAdapter() {
		if (pricestrategiesItemProvider == null) {
			pricestrategiesItemProvider = new PricestrategiesItemProvider(this);
		}

		return pricestrategiesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.occiware.clouddesigner.occi.simulation.Ondemand} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OndemandItemProvider ondemandItemProvider;

	/**
	 * This creates an adapter for a {@link org.occiware.clouddesigner.occi.simulation.Ondemand}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOndemandAdapter() {
		if (ondemandItemProvider == null) {
			ondemandItemProvider = new OndemandItemProvider(this);
		}

		return ondemandItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.occiware.clouddesigner.occi.simulation.Upfront} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UpfrontItemProvider upfrontItemProvider;

	/**
	 * This creates an adapter for a {@link org.occiware.clouddesigner.occi.simulation.Upfront}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUpfrontAdapter() {
		if (upfrontItemProvider == null) {
			upfrontItemProvider = new UpfrontItemProvider(this);
		}

		return upfrontItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.occiware.clouddesigner.occi.simulation.Auction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AuctionItemProvider auctionItemProvider;

	/**
	 * This creates an adapter for a {@link org.occiware.clouddesigner.occi.simulation.Auction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAuctionAdapter() {
		if (auctionItemProvider == null) {
			auctionItemProvider = new AuctionItemProvider(this);
		}

		return auctionItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (computesimItemProvider != null) computesimItemProvider.dispose();
		if (storagesimItemProvider != null) storagesimItemProvider.dispose();
		if (networksimItemProvider != null) networksimItemProvider.dispose();
		if (datacenterItemProvider != null) datacenterItemProvider.dispose();
		if (cloudletItemProvider != null) cloudletItemProvider.dispose();
		if (hostItemProvider != null) hostItemProvider.dispose();
		if (vmItemProvider != null) vmItemProvider.dispose();
		if (harddrivestorageItemProvider != null) harddrivestorageItemProvider.dispose();
		if (sanstorageItemProvider != null) sanstorageItemProvider.dispose();
		if (probadistribItemProvider != null) probadistribItemProvider.dispose();
		if (poissonItemProvider != null) poissonItemProvider.dispose();
		if (gaussItemProvider != null) gaussItemProvider.dispose();
		if (binomialeItemProvider != null) binomialeItemProvider.dispose();
		if (pricestrategiesItemProvider != null) pricestrategiesItemProvider.dispose();
		if (ondemandItemProvider != null) ondemandItemProvider.dispose();
		if (upfrontItemProvider != null) upfrontItemProvider.dispose();
		if (auctionItemProvider != null) auctionItemProvider.dispose();
	}

}
