/**
 * Copyright (c) 2015-2017 Obeo, Inria
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 	
 * Contributors:
 * - William Piers <william.piers@obeo.fr>
 * - Philippe Merle <philippe.merle@inria.fr>
 * - Faiez Zalila <faiez.zalila@inria.fr>
 */
package occ.simulation.provider;

import java.util.ArrayList;
import java.util.Collection;

import occ.simulation.util.SimulationAdapterFactory;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class SimulationItemProviderAdapterFactory extends SimulationAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public SimulationItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link occ.simulation.Datacenter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DatacenterItemProvider datacenterItemProvider;

	/**
	 * This creates an adapter for a {@link occ.simulation.Datacenter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDatacenterAdapter() {
		if (datacenterItemProvider == null) {
			datacenterItemProvider = new DatacenterItemProvider(this);
		}

		return datacenterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link occ.simulation.Vm} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VmItemProvider vmItemProvider;

	/**
	 * This creates an adapter for a {@link occ.simulation.Vm}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVmAdapter() {
		if (vmItemProvider == null) {
			vmItemProvider = new VmItemProvider(this);
		}

		return vmItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link occ.simulation.Host} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected HostItemProvider hostItemProvider;

	/**
	 * This creates an adapter for a {@link occ.simulation.Host}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createHostAdapter() {
		if (hostItemProvider == null) {
			hostItemProvider = new HostItemProvider(this);
		}

		return hostItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link occ.simulation.Cloudlet} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CloudletItemProvider cloudletItemProvider;

	/**
	 * This creates an adapter for a {@link occ.simulation.Cloudlet}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCloudletAdapter() {
		if (cloudletItemProvider == null) {
			cloudletItemProvider = new CloudletItemProvider(this);
		}

		return cloudletItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link occ.simulation.Harddrive} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected HarddriveItemProvider harddriveItemProvider;

	/**
	 * This creates an adapter for a {@link occ.simulation.Harddrive}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createHarddriveAdapter() {
		if (harddriveItemProvider == null) {
			harddriveItemProvider = new HarddriveItemProvider(this);
		}

		return harddriveItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link occ.simulation.Sanstorage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SanstorageItemProvider sanstorageItemProvider;

	/**
	 * This creates an adapter for a {@link occ.simulation.Sanstorage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSanstorageAdapter() {
		if (sanstorageItemProvider == null) {
			sanstorageItemProvider = new SanstorageItemProvider(this);
		}

		return sanstorageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link occ.simulation.Pricestrategy} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PricestrategyItemProvider pricestrategyItemProvider;

	/**
	 * This creates an adapter for a {@link occ.simulation.Pricestrategy}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPricestrategyAdapter() {
		if (pricestrategyItemProvider == null) {
			pricestrategyItemProvider = new PricestrategyItemProvider(this);
		}

		return pricestrategyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link occ.simulation.Spot} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SpotItemProvider spotItemProvider;

	/**
	 * This creates an adapter for a {@link occ.simulation.Spot}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSpotAdapter() {
		if (spotItemProvider == null) {
			spotItemProvider = new SpotItemProvider(this);
		}

		return spotItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link occ.simulation.Ondemand} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OndemandItemProvider ondemandItemProvider;

	/**
	 * This creates an adapter for a {@link occ.simulation.Ondemand}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOndemandAdapter() {
		if (ondemandItemProvider == null) {
			ondemandItemProvider = new OndemandItemProvider(this);
		}

		return ondemandItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link occ.simulation.Upfront} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UpfrontItemProvider upfrontItemProvider;

	/**
	 * This creates an adapter for a {@link occ.simulation.Upfront}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUpfrontAdapter() {
		if (upfrontItemProvider == null) {
			upfrontItemProvider = new UpfrontItemProvider(this);
		}

		return upfrontItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (datacenterItemProvider != null) datacenterItemProvider.dispose();
		if (vmItemProvider != null) vmItemProvider.dispose();
		if (hostItemProvider != null) hostItemProvider.dispose();
		if (cloudletItemProvider != null) cloudletItemProvider.dispose();
		if (harddriveItemProvider != null) harddriveItemProvider.dispose();
		if (sanstorageItemProvider != null) sanstorageItemProvider.dispose();
		if (pricestrategyItemProvider != null) pricestrategyItemProvider.dispose();
		if (spotItemProvider != null) spotItemProvider.dispose();
		if (ondemandItemProvider != null) ondemandItemProvider.dispose();
		if (upfrontItemProvider != null) upfrontItemProvider.dispose();
	}

}
